baseurl = "//stormovsky.github.io/PORES/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "PORES"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"

	analytics = "code-here"

	#email = "alexurquhart@gmail.com"

        header="News about project"

	profilepic = "/img/UKF-logo.png"

	title = "Plymouth Marine Laboratory Research Visit"
	subtitle = "Connectivity Program, Gaining Experience Grant Unity through Knowledge Fund - UKF  http://www.ukf.hr/"

	# Social buttons for sidebar
	# Each of these are optional
        #[[params.socialbuttons]]
	#faicon = "github"
	#url = "https://github.com/alexurquhart"
	#[[params.socialbuttons]]
	#faicon = "twitter"
	#url = "https://twitter.com/alexanderurq"
	#[[params.socialbuttons]]
	#faicon = "linkedin"
	#url = "https://linkedin.com"
	#[[params.socialbuttons]]
	#faicon = "google-plus"
	#url = "https://plus.google.com/+YourID"

	[[params.navlinks]]
	name = "About project PORES"
	url = "about/"

	[[params.navlinks]]
	name = "News"
	url = "post/"

	#[[params.navlinks]]
	#name = "TRACMASS"
	#url = "TRACMASS/"
